name: Build LibV2Ray AAR Full Core

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-aar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.22'

    - name: Set up Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set Android NDK Environment Variable
      run: |
        echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk-bundle" >> $GITHUB_ENV
        echo "NDK_HOME=$ANDROID_SDK_ROOT/ndk-bundle" >> $GITHUB_ENV

    - name: Install Gomobile & Gobind
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        go install golang.org/x/mobile/cmd/gobind@latest
        gomobile init

    - name: Clone Source Code v2rayNG Lib
      run: |
        git clone https://github.com/2dust/v2rayNG.git

    - name: Compile Go Core + Tun2Socks -> libv2ray.aar
      run: |
        TARGET_DIR=$(find v2rayNG -type f -name "go.mod" -exec dirname {} \; | head -n 1)
        echo "Ketemu folder Go di: $TARGET_DIR"
        cd "$TARGET_DIR"

        # Tembak dependency gobind & mobile ke go.mod
        go get golang.org/x/mobile/cmd/gobind
        go get golang.org/x/mobile
        go mod tidy

        # Build AAR
        gomobile bind -v -target=android/arm64,android/arm -androidapi 21 -javapkg=libv2ray -o $GITHUB_WORKSPACE/libv2ray.aar .

    - name: Create GitHub Release & Upload AAR
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.0
        name: "LibV2Ray Core Native AAR v1.0.0"
        draft: false
        prerelease: false
        files: libv2ray.aar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
